### ISSUE TITLE
Mismatched images and labels for semantic segmentation

### ISSUE THREAD

**Issue by rod409** [bdd100k/bdd100k#103]
I found a few images and labels that do not match in the images/10k images for semantic segmentation and the corresponding bitmasks downloaded in labels/sem_seg/masks. These are the following files

In images path but not in labels:
- train/3d581db5-2564fb7e.jpg
- train/52e3fd10-c205dec2.jpg
- train/781756b0-61e0a182.jpg
- train/78ac84ba-07bd30c2.jpg
- val/80a9e37d-e4548ac1.jpg
- val/9342e334-33d167eb.jpg

In labels path but not in images:
- train/fee92217-63b3f87f.png
- train/ff1e4d6d-f4d85cfd.png
- train/ff3d3536-04986e25.png
- train/ff3da814-c3463a43.png
- val/ff55861e-a06b953c.png
- val/ff7b98c7-3cb964ac.png

I am able to train a model successfully after removing these images but wanted to bring this to your attention.

Thanks.

**Comment by XiaLiPKU** [comment]
> I found a few images and labels that do not match in the images/10k images for semantic segmentation and the corresponding bitmasks downloaded in labels/sem_seg/masks. These are the following files
> 
> In images path but not in labels:
> 
> * train/3d581db5-2564fb7e.jpg
> * train/52e3fd10-c205dec2.jpg
> * train/781756b0-61e0a182.jpg
> * train/78ac84ba-07bd30c2.jpg
> * val/80a9e37d-e4548ac1.jpg
> * val/9342e334-33d167eb.jpg
> 
> In labels path but not in images:
> 
> * train/fee92217-63b3f87f.png
> * train/ff1e4d6d-f4d85cfd.png
> * train/ff3d3536-04986e25.png
> * train/ff3da814-c3463a43.png
> * val/ff55861e-a06b953c.png
> * val/ff7b98c7-3cb964ac.png
> 
> I am able to train a model successfully after removing these images but wanted to bring this to your attention.
> 
> Thanks.

Thanks for informing!
We also notice this problem and would like to publish a new version of the image zip these days

**Comment by griffintin** [comment]
@XiaLiPKU 

could you please have a look at the above validation  images of wrong labels for instances segmentation?
I would like to mention that, in training labels, I found similar wrong labels.
But sorry that  I am not able to check all 7000 images to give you details.

**Comment by XiaLiPKU** [comment]
> @XiaLiPKU
> 
> could you please have a look at the above validation images of wrong labels for instances segmentation?
> I would like to mention that, in training labels, I found similar wrong labels.
> But sorry that I am not able to check all 7000 images to give you details.

All thanks for your mentioning.
Currently, we have no method to deal with these errors, except to find them and let the labelers re-label them.
This issue is significant to us, so we will try to solve it as quickly as we can.

**Comment by XiaLiPKU** [comment]
> > I found a few images and labels that do not match in the images/10k images for semantic segmentation and the corresponding bitmasks downloaded in labels/sem_seg/masks. These are the following files
> > In images path but not in labels:
> > 
> > * train/3d581db5-2564fb7e.jpg
> > * train/52e3fd10-c205dec2.jpg
> > * train/781756b0-61e0a182.jpg
> > * train/78ac84ba-07bd30c2.jpg
> > * val/80a9e37d-e4548ac1.jpg
> > * val/9342e334-33d167eb.jpg
> > 
> > In labels path but not in images:
> > 
> > * train/fee92217-63b3f87f.png
> > * train/ff1e4d6d-f4d85cfd.png
> > * train/ff3d3536-04986e25.png
> > * train/ff3da814-c3463a43.png
> > * val/ff55861e-a06b953c.png
> > * val/ff7b98c7-3cb964ac.png
> > 
> > I am able to train a model successfully after removing these images but wanted to bring this to your attention.
> > Thanks.
> 
> Thanks for informing!
> We also notice this problem and would like to publish a new version of the image zip these days


We shall view new downloading files today or tomorrow.
To quickly solve this current problem, you can use the patch here: [patch.tar.gz](https://github.com/bdd100k/bdd100k/files/6494899/patch.tar.gz). Hope this can help you

**Comment by pcicales** [comment]
Hello, were the download files updated? I downloaded last week.

**Comment by XiaLiPKU** [comment]
> Hello, were the download files updated? I downloaded last week.

Sorry to let you wait.
We published a new version of image downloading files.
You can now download them on the website: https://bdd-data.berkeley.edu/
Now, 100k and 10k images are separated into two files.
For more information, you may refer to: https://doc.bdd100k.com/download.html#id1

**Comment by pcicales** [comment]
@XiaLiPKU are the labels updated as well?

**Comment by guifentian** [comment]
@XiaLiPKU @fyu 

I am trying again but to use the latest 10k images/labels , and the newest code for instance segmentation.
The labels are still wrong as I reported  here https://github.com/bdd100k/bdd100k/issues/103#issuecomment-837625220

Since I reported the miss labels in May, nothing improvement was done.
Really sad to find this.

**Comment by thomasehuang** [comment]
These issues should be already addressed, let us know if it's still an issue.
